# Generated by Django 6.0.4 on 2026-07-09 02:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_add_otp_expiration_and_limit'),
    ]

    operations = [
        # NOTE: DeleteModel for 'PreDefinedScholarship_Sv' was removed.
        # On a fresh database the model was never created by a preceding migration
        # in the current chain, causing a KeyError in state_forwards. The table
        # is simply skipped here; no data loss occurs.

        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the coupon was created', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable/disable this coupon'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='last_used',
            field=models.DateTimeField(blank=True, help_text='Last time this coupon was used', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum times coupon can be used (leave blank for unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used'),
        ),
        migrations.AddField(
            model_name='predefinedscholarship',
            name='study_level',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate/Bachelor'), ('master', "Master's"), ('phd', 'PhD/Doctoral'), ('all', 'All Levels')], default='all', help_text='Target study level for this scholarship', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='otp_failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scholarshipapplicant',
            name='pdf_created_at',
            field=models.DateTimeField(blank=True, help_text='When the PDF was generated. Used for 24-hour auto-deletion.', null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='active_dataset_index_name',
            field=models.CharField(default='scholarships-index-latest', help_text="The name of the Pinecone index to use when 'Use Default Dataset Index' is unchecked.", max_length=255, verbose_name='Active Dataset Index Name'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='available_dataset_indices',
            field=models.JSONField(blank=True, default=dict, help_text='JSON map of available dataset index names and their metadata.', verbose_name='Available Dataset Indices'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_query_prompt_individual',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM filter when user type is Individual. Leave blank to use the default prompt above.', verbose_name='Custom LLM Filter Prompt - Individual Users'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_query_prompt_organization',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM filter when user type is Organization. Leave blank to use the built-in organization prompt.', verbose_name='Custom LLM Filter Prompt - Organization Users'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_reranker_prompt_individual',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM reranker when user type is Individual. Leave blank to use the default prompt above.', verbose_name='Custom LLM Reranker Prompt - Individual Users'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_reranker_prompt_organization',
            field=models.TextField(blank=True, default='', help_text='Custom system prompt for LLM reranker when user type is Organization. Leave blank to use the built-in organization prompt.', verbose_name='Custom LLM Reranker Prompt - Organization Users'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='last_active_dataset_index',
            field=models.CharField(default='scholarships-index-latest', help_text='Previous active index to detect when user changes it', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='llm_reranker',
            field=models.TextField(blank=True, default='You are ranking scholarships for a user on a Swedish stipendieportal. The goal is to present scholarships in order of how useful they are to this specific user.\n\nUSER PROFILE\nPurpose: {user_purpose}\nStudy level: {study_level}\nDomain: {user_domain}\n\nCORE RANKING PRINCIPLE\nA broadly applicable scholarship the user clearly qualifies for is more valuable than a niche scholarship requiring a very specific subspecialty match. Wide eligibility plus relevant domain beats narrow eligibility plus perfect domain match. Niche scholarships rank higher only when the user explicitly mentioned that subspecialty in their purpose.\n\nRANKING TIERS\nTIER A. Broadly eligible scholarships. Open to all university students at the user\'s study level, or to a wide range of fields. The user clearly qualifies without needing a specific subspecialty.\nTIER B. Domain-relevant scholarships. Targets the user\'s broad domain (law, technology, business, medicine) without requiring a specific subspecialty.\nTIER C. Niche subject-specific scholarships. Targets a specific subspecialty within the user\'s domain. The user qualifies but eligibility is narrow.\nTIER D. Borderline or mixed scholarships. Domain match is weak, the scholarship is primarily research-oriented with only a thin student pathway, or eligibility is unclear.\n\nTIE-BREAKER WITHIN A TIER\nPrefer scholarships that mention a clear application process, a deadline, and an explicit monetary value. Prefer scholarships in the user\'s municipality or county when geography is mentioned. Otherwise keep the order stable.\n\nOUTPUT\nReturn an ordered JSON array of scholarship names, best first. No commentary.\nExample: ["Scholarship A", "Scholarship B", "Scholarship C"]', help_text='Optional system prompt for LLM reranker. Leave blank to use default behavior.', verbose_name='LLM reranker system prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='upload_in_progress',
            field=models.BooleanField(default=False, help_text='Tracks if an upload is currently running to prevent duplicate uploads'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_dataset',
            field=models.BooleanField(default=True, help_text="Check to use the hardcoded default index 'scholarships-index-latest' from stipo54.py. Uncheck to use a custom dataset index.", verbose_name='Use Default Dataset Index'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_query_filter_base',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default filter prompt', verbose_name='Use Default - LLM Filter Base Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_query_filter_individual',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default filter prompt for individual users', verbose_name='Use Default - Individual Filter Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_query_filter_organization',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default filter prompt for organization users', verbose_name='Use Default - Organization Filter Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_reranker_base',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default reranker prompt', verbose_name='Use Default - LLM Reranker Base Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_reranker_individual',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default reranker prompt for individual users', verbose_name='Use Default - Individual Reranker Prompt'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='use_default_reranker_organization',
            field=models.BooleanField(default=True, help_text='Check to use the hardcoded default reranker prompt for organization users', verbose_name='Use Default - Organization Reranker Prompt'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, default=app.models.random_string, max_length=7, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='predefinedscholarship',
            name='subject',
            field=models.CharField(blank=True, choices=[('always', 'Always'), ('other', 'Other'), ('engineering_technology', 'Engineering and Technology'), ('economics_business', 'Economics, Business Administration & Management'), ('medicine_health', 'Medicine and Health Sciences'), ('cs_it_data', 'Computer Science / IT / Data Science'), ('education_pedagogy', 'Education and Pedagogy'), ('psychology_behavioral', 'Psychology and Behavioral Sciences'), ('law_political', 'Law and Political Science'), ('environment_sustainability', 'Environmental and Sustainability Sciences'), ('design_architecture_arts', 'Design, Architecture, and Creative Arts'), ('biology_chemistry_life', 'Biology, Chemistry, and Life Sciences'), ('public_health_epidemiology', 'Public Health / Epidemiology'), ('eng_tech_advanced', 'Engineering & Technology (cybersecurity, supply chain, machine)'), ('business_management', 'Business & Management (Finance, Accounting, International Business)'), ('cs_digital_data_advanced', 'Computer Science / Digital Business / Data Science'), ('education_didactics', 'Education & Pedagogy (Didactics, Leadership)'), ('environment_urban', 'Environmental & Sustainability Sciences / Urban Planning'), ('life_science_biotech', 'Life Sciences & Biotechnology'), ('law_llm', 'Law (LL.M / Legal Studies)'), ('design_creative_advanced', 'Design, Architecture & Creative Arts'), ('social_sciences', 'Social Sciences (Psychology, Social Work, Political Science)'), ('phd_engineering_technology', 'Engineering/Technology | Teknik och ingenjörsvetenskap'), ('phd_economics', 'Economics | Ekonomi'), ('phd_medicine', 'Medicine | Medicin'), ('phd_law', 'Law | Juridik'), ('phd_arts_culture', 'Arts/Culture | Konst/Kultur')], null=True),
        ),
        migrations.AlterField(
            model_name='scholarshipapplicant',
            name='otp',
            field=models.CharField(default=app.models.create_otp),
        ),
        migrations.AlterField(
            model_name='scholarshipapplicant',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.generate_pdf_path),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='query_template',
            field=models.TextField(default='You are a scholarship inclusion filter. Your only job is to remove scholarships the user cannot realistically apply for. Default action is INCLUDE. Only exclude when the mismatch is clear and unambiguous.\n\nUSER PROFILE\nPurpose: {user_purpose}\nStudy level: {study_level_context}\nDomain: {user_domain}\nGender: {gender}\n\nEXCLUSION RULES\nExclude a scholarship only if one of the following is clearly stated in its purpose text:\n- The scholarship is exclusively for the opposite gender of the user.\n- The scholarship is exclusively for doctoral or postdoc researchers and the user is an undergraduate, with no language about student pathway, thesis work, or studerande, elev, kandidat.\n- The scholarship is for primary school or gymnasium only, with no university pathway mentioned.\n- The scholarship funds an institution, professorship, chair, faculty operation, or research infrastructure with no individual application path for students.\n- The scholarship is exclusively for a clearly unrelated domain such that there is zero realistic connection to the user\'s stated purpose.\n\nDEFAULT INCLUSION RULE\nWhen in doubt, include. Broad scholarships open to all university students, scholarships with mixed purpose, and scholarships that mention the user\'s broad field even briefly should always be included.\n\nOUTPUT\nReturn a JSON array of included scholarship names, nothing else.\nExample: ["Scholarship A", "Scholarship B"]', verbose_name='LLM filter system prompt'),
        ),
    ]
