# Generated by Django 5.2.16 on 2026-07-23 03:09

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_cookie_consent_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarships_db_file', models.FileField(blank=True, null=True, upload_to=app.models.scholarship_db_path, verbose_name='Scholarships DB file')),
                ('use_default_dataset', models.BooleanField(default=True, help_text="Check to use the hardcoded default index 'scholarships-index-latest'.", verbose_name='Use Default Dataset Index')),
                ('dataset_index_name', models.CharField(default='scholarships-index-latest', help_text='Name of the Pinecone index to use when not using the default dataset.', max_length=255, verbose_name='Dataset Index Name')),
                ('pinecone_updated', models.BooleanField(default=False, help_text='Set to true when this dataset has been successfully uploaded to Pinecone.', verbose_name='Pinecone updated')),
                ('upload_in_progress', models.BooleanField(default=False, help_text='Tracks whether a dataset upload is currently running.', verbose_name='Upload in progress')),
                ('upload_status', models.CharField(choices=[('not_started', 'Not Started'), ('partial', 'Partial Upload'), ('complete', 'Complete'), ('failed', 'Failed')], default='not_started', help_text='High-level status of the dataset upload.', max_length=50, verbose_name='Upload Status')),
                ('upload_progress', models.PositiveIntegerField(default=0, help_text='Integer percent progress (0-100) updated during background upload.', verbose_name='Upload Progress (%)')),
                ('rows_uploaded', models.PositiveIntegerField(default=0, help_text='Number of rows successfully uploaded to the index.', verbose_name='Rows uploaded')),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total number of rows in the dataset when upload started.', verbose_name='Total rows')),
                ('upload_error_message', models.TextField(blank=True, default='', help_text='If the upload fails, a short error message is recorded here.', verbose_name='Upload error message')),
                ('last_uploaded_at', models.DateTimeField(blank=True, help_text='Timestamp when this dataset was successfully uploaded to Pinecone.', null=True, verbose_name='Last uploaded at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataset Upload',
                'verbose_name_plural': 'Dataset Uploads',
            },
        ),
    ]
