# Generated by Django 5.2.16 on 2026-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_siteconfig_active_dataset_index_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile_icon',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('Non-binary', 'Non-binary'), ('prefer to say', 'Prefer to say'), ('others', 'Others')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
