# Generated by Django 5.2.8 on 2026-08-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_review_profile_icon_review_reviewer_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('Non-binary', 'Non-binary'), ('prefer not to say', 'Prefer not to say'), ('others', 'Others')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='admin_check',
            field=models.BooleanField(default=True, help_text='If checked (True), applicants will receive report emails when application is processed. If unchecked (False), no emails will be sent.', verbose_name='Admin Check (Send Report Emails)'),
        ),
    ]
